runtime: nodejs
env: flex

env_variables:
  SQL_USER: ""
  SQL_PASSWORD: ""
  SQL_DATABASE: ""
  INSTANCE_CONNECTION_NAME: ""   # <PROJECT_ID>:<REGION>:<INSTANCE_NAME>

beta_settings:
  cloud_sql_instances: ""   # <PROJECT_ID>:<REGION>:<INSTANCE_NAME>
